version: '3.4'
services:

  store:
    container_name: "store"
    image: "samply/blaze:0.10.3"
    environment:
      BASE_URL: "http://store:8080"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
    networks:
      - "samply"
    volumes:
      - "store-db-data:/app/data"
    ports:
      - "8080:8080"
    restart: "always"

  blaze-quality-reporting-ui:
    container_name: "blaze-quality-reporting-ui"
    image: "samply/blaze-quality-reporting-ui:0.7.2"
    networks:
      - "samply"
    ports:
      - "8081:80"
    restart: "always"

  connector:
    container_name: "connector"
    image: "samply/share-client:samply-7.2.4"
    environment:
      POSTGRES_HOST: "connector-db"
      POSTGRES_DB: "samply.connector"
      POSTGRES_USER: "samply"
      POSTGRES_PASS: "samply"
      STORE_URL: "http://store:8080/fhir"
      QUERY_LANGUAGE: "CQL"
      MDR_URL: "https://mdr.germanbiobanknode.de/v3/api/mdr"
    networks:
      - "samply"
      - "connector-db"
    ports:
      - "8082:8080"
    depends_on:
      - "connector-db"
    restart: "always"

  connector-db:
    container_name: "connector-db"
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: "samply"
      POSTGRES_PASSWORD: "samply"
      POSTGRES_DB: "samply.connector"
    networks:
      - "connector-db"
    volumes:
      - "connector-db-data:/var/lib/postgresql/data"
    restart: "always"

  searchbroker-ui:
    container_name: "searchbroker-ui"
    image: samply/sample-locator:2.0.1
    environment:
      AUTH_CLIENT_ID:       "88ad6e4f-af9b-430a-8884-394e29cd10c1"
      MOLGENIS_USERNAME:    "DUMMY"
      MOLGENIS_PASSWORD:    "DUMMY"
      SEARCHBROKER_URL:     "http://<YOUR_IP>:8086/broker"
      SAMPLELOCATOR_URL:    "http://<YOUR_IP>:8085"
      NEGOTIATOR_URL:       "https://negotiator.bbmri-eric.eu"
      AUTH_HOST:            "https://login.bbmri-eric.eu"
      MDR_API_URL:          "https://mdr.bbmri.de/v3/api/mdr"
      MDR_NAMESPACE:        "mdr16"
      MDR_LANGUAGE:         "en"
      MDR_MAPPING:          "[{\"nameOfEnum\": \"DONOR\",\"urn\": \"urn:mdr16:dataelementgroup:5:1\"},{\"nameOfEnum\": \"SAMPLE\",\"urn\": \"urn:mdr16:dataelementgroup:3:1\"},{\"nameOfEnum\": \"EVENT\", \"urn\": \"urn:mdr16:dataelementgroup:6:1\"}]"
      MDR_FIELD_PROPERTIES: "[{\"urn\": \"urn:mdr16:dataelement:29:1\",\"placeholder\": \"\",\"unit\": \"kg\"},{\"urn\": \"urn:mdr16:dataelement:30:1\",\"placeholder\": \"\",\"unit\": \"cm\"},{\"urn\": \"urn:mdr16:dataelement:28:1\",\"placeholder\": \"\",\"unit\": \"years\"},{\"urn\": \"urn:mdr16:dataelement:14:1\",\"placeholder\": \"\",\"unit\": \"years\"},{\"urn\": \"urn:mdr16:dataelement:27:1\",\"placeholder\": \"e.g. C25.1\",\"unit\": \"\"}]"
      MDR_HIDDEN:           "[\"urn:mdr16:dataelement:1:1\",\"urn:mdr16:dataelement:25:1\",\"urn:mdr16:dataelement:34:1\",\"urn:mdr16:dataelement:18:1\",\"urn:mdr16:dataelement:11:1\",\"urn:mdr16:dataelement:19:1\",\"urn:mdr16:dataelement:30:1\",\"urn:mdr16:dataelement:4:1\",\"urn:mdr16:dataelement:21:1\",\"urn:mdr16:dataelement:22:1\",\"urn:mdr16:dataelement:24:1\",\"urn:mdr16:dataelement:13:1\"]"
    networks:
      - samply
    restart: always
    ports:
    - "8085:80"

  searchbroker:
    container_name: "searchbroker"
    image: samply/searchbroker:7.1.0
    environment:
      AUTH_CLIENT_ID:     "88ad6e4f-af9b-430a-8884-394e29cd10c1"
      POSTGRES_HOST:      "searchbroker-db"
      POSTGRES_DB:        "searchbroker"
      POSTGRES_PORT:      "5432"
      POSTGRES_USER:      "searchbroker"
      POSTGRES_PASS:      "searchbroker"
      MAIL_HOST:          "DUMMY"
      MAIL_FROM_ADDRESS:  "DUMMY"
      MAIL_FROM_NAME:     "DUMMY"
      AUTH_HOST:          "https://login.bbmri-eric.eu"
      AUTH_PUBLIC_KEY:    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKvsfThd4XO/J5PDlgnmCZ3vGB8MRwcK4rJ42xO/xVmtwkxV8ZW4LIbRE+uQn4EsyTY8ke9do2sSUHGSIHh6T0OR1nm9eljOEXwO6/kYPJbVvEYRIQaZ5kvuCZEP9dcyHwgaN9thHpo2n71GpVo+kZ/KhUY8XHU7PIUokCPIQrF20CvANa2h8htJMp3mIIBJ2j1sf7qfLo2QAJO5p92zASwPpZSebOFhqU5005Qp7uNB+Rv+1rwL2mclEcXRjmNQmStThOetZLgReoszE3obHyW65UprY269ulKAyqPVm653jtp5aYAt/sP1twgW9UY2+lkOMMpLYwZkTcg3eAW0vQIDAQAB"
      STATISTICS_MAILS:   "${STATISTICS_MAILS}"
      CATALINA_OPTS:      '"-Xmx1g"'
    networks:
    - samply
    - searchbroker-db
    depends_on:
    - searchbroker-db
    restart: always
    ports:
     - "8086:8080"

  searchbroker-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER:      "searchbroker"
      POSTGRES_PASSWORD:  "searchbroker"
      POSTGRES_DB:        "searchbroker"
    networks:
    - searchbroker-db
    expose:
    - 5432
    volumes:
    - searchbroker-db-data:/var/lib/postgresql/data
    restart: always


networks:
  samply:
    driver: "bridge"
  connector-db:
    driver: "bridge"
  searchbroker-db:
    driver: bridge

volumes:
  store-db-data:
    name: "store-db-data"
  connector-db-data:
    name: "connector-db-data"
  searchbroker-db-data:
